/*
 * To_Do_wpfweb, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using To_Do_ApiCli.Client;
using To_Do_ApiCli.Api;
// uncomment below to import models
//using To_Do_ApiCli.Model;

namespace To_Do_ApiCli.Test.Api
{
    /// <summary>
    ///  Class for testing ToDoApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class ToDoApiTests : IDisposable
    {
        private ToDoApi instance;

        public ToDoApiTests()
        {
            instance = new ToDoApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ToDoApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' ToDoApi
            //Assert.IsType<ToDoApi>(instance);
        }

        /// <summary>
        /// Test ToDoGet
        /// </summary>
        [Fact]
        public void ToDoGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.ToDoGet();
            //Assert.IsType<List<ToDo>>(response);
        }

        /// <summary>
        /// Test ToDoIdDelete
        /// </summary>
        [Fact]
        public void ToDoIdDeleteTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string id = null;
            //instance.ToDoIdDelete(id);
        }

        /// <summary>
        /// Test ToDoIdGet
        /// </summary>
        [Fact]
        public void ToDoIdGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string id = null;
            //var response = instance.ToDoIdGet(id);
            //Assert.IsType<ToDo>(response);
        }

        /// <summary>
        /// Test ToDoPost
        /// </summary>
        [Fact]
        public void ToDoPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //ToDo toDo = null;
            //instance.ToDoPost(toDo);
        }
    }
}
