// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace To_Do_wpfweb.Migrations
{
    [DbContext(typeof(To_Do_Context))]
    partial class To_Do_ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.6");

            modelBuilder.Entity("To_Do_Project.To_Do", b =>
                {
                    b.Property<string>("TitleId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Plan")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("TitleId");

                    b.ToTable("To_Do_DataBase_List");
                });
#pragma warning restore 612, 618
        }
    }
}
