/*
 * To_Do_wpfweb, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using To_Do_ApiCli.Api;
using To_Do_ApiCli.Model;
using To_Do_ApiCli.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace To_Do_ApiCli.Test.Model
{
    /// <summary>
    ///  Class for testing ToDo
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ToDoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ToDo
        //private ToDo instance;

        public ToDoTests()
        {
            // TODO uncomment below to create an instance of ToDo
            //instance = new ToDo();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ToDo
        /// </summary>
        [Fact]
        public void ToDoInstanceTest()
        {
            // TODO uncomment below to test "IsType" ToDo
            //Assert.IsType<ToDo>(instance);
        }


        /// <summary>
        /// Test the property 'Date'
        /// </summary>
        [Fact]
        public void DateTest()
        {
            // TODO unit test for the property 'Date'
        }
        /// <summary>
        /// Test the property 'Plan'
        /// </summary>
        [Fact]
        public void PlanTest()
        {
            // TODO unit test for the property 'Plan'
        }
        /// <summary>
        /// Test the property 'TitleId'
        /// </summary>
        [Fact]
        public void TitleIdTest()
        {
            // TODO unit test for the property 'TitleId'
        }

    }

}
